# manufacturer_config.py

# Updated on: 2025-07-14 15:05:08
# AutoPacific extraction: 2025-07-14T14:48:12.952709

# Vehicle categories based on Jamaica's importation age limits effective November 6, 2019
# Categories: motorcycles_atvs(5), cars(6), light_commercial(6-10), commercial(12-30), heavy_duty(30)

manufacturer_configs = {
    "TOYOTA": {
        "86": {"category": "cars", "age_limit": 6},
        "4RUNNER": {"category": "cars", "age_limit": 6},
        "ALLEX": {"category": "cars", "age_limit": 6},
        "ALLION": {"category": "cars", "age_limit": 6},
        "ALPHARD": {"category": "cars", "age_limit": 6},
        "ALPHARD G": {"category": "cars", "age_limit": 6},
        "ALPHARD HYBRID": {"category": "cars", "age_limit": 6},
        "ALPHARD V": {"category": "cars", "age_limit": 6},
        "ALTEZZA": {"category": "cars", "age_limit": 6},
        "ALTEZZA GITA": {"category": "cars", "age_limit": 6},
        "AQUA": {"category": "cars", "age_limit": 6},
        "ARISTO": {"category": "cars", "age_limit": 6},
        "AURIS": {"category": "cars", "age_limit": 6},
        "AVENSIS": {"category": "cars", "age_limit": 6},
        "AVENSIS WAGON": {"category": "cars", "age_limit": 6},
        "BB": {"category": "cars", "age_limit": 6},
        "BELTA": {"category": "cars", "age_limit": 6},
        "BLADE": {"category": "cars", "age_limit": 6},
        "BLIZZARD": {"category": "cars", "age_limit": 6},
        "BREVIS": {"category": "cars", "age_limit": 6},
        "BZ4X": {"category": "cars", "age_limit": 6},
        "C-HR": {"category": "cars", "age_limit": 6},
        "C+POD": {"category": "cars", "age_limit": 6},
        "CALDINA": {"category": "cars", "age_limit": 6},
        "CAMI": {"category": "cars", "age_limit": 6},
        "CAMROAD": {"category": "commercial", "age_limit": 15},
        "CAMRY": {"category": "cars", "age_limit": 6},
        "CAMRY GRACIA": {"category": "cars", "age_limit": 6},
        "CARINA": {"category": "cars", "age_limit": 6},
        "CARINA ED": {"category": "cars", "age_limit": 6},
        "CARINA SURF": {"category": "cars", "age_limit": 6},
        "CELICA": {"category": "cars", "age_limit": 6},
        "CELICA XX": {"category": "cars", "age_limit": 6},
        "CELSIOR": {"category": "cars", "age_limit": 6},
        "CENTURY": {"category": "cars", "age_limit": 6},
        "CHASER": {"category": "cars", "age_limit": 6},
        "CLASSIC": {"category": "cars", "age_limit": 6},
        "COASTER": {"category": "commercial", "age_limit": 15},
        "COPEN": {"category": "cars", "age_limit": 6},
        "COROLLA": {"category": "cars", "age_limit": 6},
        "COROLLA AXIO": {"category": "cars", "age_limit": 6},
        "COROLLA CROSS": {"category": "cars", "age_limit": 6},
        "COROLLA FIELDER": {"category": "cars", "age_limit": 6},
        "COROLLA II": {"category": "cars", "age_limit": 6},
        "COROLLA LEVIN": {"category": "cars", "age_limit": 6},
        "COROLLA RUMION": {"category": "cars", "age_limit": 6},
        "COROLLA RUNX": {"category": "cars", "age_limit": 6},
        "COROLLA SPACIO": {"category": "cars", "age_limit": 6},
        "COROLLA SPORT": {"category": "cars", "age_limit": 6},
        "COROLLA TOURING WAGON": {"category": "cars", "age_limit": 6},
        "COROLLA VAN": {"category": "light_commercial", "age_limit": 10},
        "COROLLA WAGON": {"category": "cars", "age_limit": 6},
        "CORONA": {"category": "cars", "age_limit": 6},
        "CORONA EXIV": {"category": "cars", "age_limit": 6},
        "CORONA PREMIO": {"category": "cars", "age_limit": 6},
        "CORSA": {"category": "cars", "age_limit": 6},
        "CRESTA": {"category": "cars", "age_limit": 6},
        "CROWN": {"category": "cars", "age_limit": 6},
        "CROWN ATHLETE": {"category": "cars", "age_limit": 6},
        "CROWN COMFORT": {"category": "cars", "age_limit": 6},
        "CROWN CROSSOVER": {"category": "cars", "age_limit": 6},
        "CROWN ESTATE": {"category": "cars", "age_limit": 6},
        "CROWN HYBRID": {"category": "cars", "age_limit": 6},
        "CROWN MAJESTA": {"category": "cars", "age_limit": 6},
        "CROWN SPORT": {"category": "cars", "age_limit": 6},
        "CROWN STATION WAGON": {"category": "cars", "age_limit": 6},
        "CROWN VAN": {"category": "light_commercial", "age_limit": 10},
        "CURREN": {"category": "cars", "age_limit": 6},
        "CYNOS": {"category": "cars", "age_limit": 6},
        "DUET": {"category": "cars", "age_limit": 6},
        "DYNA": {"category": "commercial", "age_limit": 20},
        "DYNA DUMP": {"category": "commercial", "age_limit": 25},
        "DYNA TRUCK": {"category": "commercial", "age_limit": 20},
        "ESQUIRE": {"category": "cars", "age_limit": 6},
        "ESTIMA": {"category": "cars", "age_limit": 6},
        "ESTIMA HYBRID": {"category": "cars", "age_limit": 6},
        "ESTIMA L": {"category": "cars", "age_limit": 6},
        "ESTIMA LUCIDA": {"category": "cars", "age_limit": 6},
        "ESTIMA T": {"category": "cars", "age_limit": 6},
        "FJ CRUISER": {"category": "cars", "age_limit": 6},
        "FUN CARGO": {"category": "cars", "age_limit": 6},
        "GAYA": {"category": "cars", "age_limit": 6},
        "GR COROLLA": {"category": "cars", "age_limit": 6},
        "GR YARIS": {"category": "cars", "age_limit": 6},
        "GR86": {"category": "cars", "age_limit": 6},
        "GRANACE": {"category": "light_commercial", "age_limit": 10},
        "GRAND HIACE": {"category": "light_commercial", "age_limit": 10},
        "GRANVIA": {"category": "cars", "age_limit": 6},
        "HARRIER": {"category": "cars", "age_limit": 6},
        "HARRIER HYBRID": {"category": "cars", "age_limit": 6},
        "HIACE": {"category": "light_commercial", "age_limit": 10},
        "HIACE COMMUTER": {"category": "light_commercial", "age_limit": 10},
        "HIACE REGIUS": {"category": "light_commercial", "age_limit": 10},
        "HIACE TRUCK": {"category": "light_commercial", "age_limit": 10},
        "HIACE VAN": {"category": "light_commercial", "age_limit": 10},
        "HIACE WAGON": {"category": "light_commercial", "age_limit": 10},
        "HILUX PICK UP": {"category": "light_commercial", "age_limit": 6},
        "HILUX SPORTS PICK UP": {"category": "light_commercial", "age_limit": 6},
        "HILUX SURF": {"category": "cars", "age_limit": 6},
        "IPSUM": {"category": "cars", "age_limit": 6},
        "IQ": {"category": "cars", "age_limit": 6},
        "ISIS": {"category": "cars", "age_limit": 6},
        "IST": {"category": "cars", "age_limit": 6},
        "JPN TAXI": {"category": "cars", "age_limit": 6},
        "KLUGER": {"category": "cars", "age_limit": 6},
        "KLUGER HYBRID": {"category": "cars", "age_limit": 6},
        "KLUGER V": {"category": "cars", "age_limit": 6},
        "LAND CRUISER": {"category": "cars", "age_limit": 6},
        "LAND CRUISER 100": {"category": "cars", "age_limit": 6},
        "LAND CRUISER 250": {"category": "cars", "age_limit": 6},
        "LAND CRUISER 40": {"category": "cars", "age_limit": 6},
        "LAND CRUISER 60": {"category": "cars", "age_limit": 6},
        "LAND CRUISER 70": {"category": "cars", "age_limit": 6},
        "LAND CRUISER 80": {"category": "cars", "age_limit": 6},
        "LAND CRUISER PRADO": {"category": "cars", "age_limit": 6},
        "LITE ACE NOAH": {"category": "light_commercial", "age_limit": 10},
        "LITE ACE TRUCK": {"category": "light_commercial", "age_limit": 6},
        "LITE ACE VAN": {"category": "light_commercial", "age_limit": 10},
        "LITE ACE WAGON": {"category": "cars", "age_limit": 6},
        "MARK II": {"category": "cars", "age_limit": 6},
        "MARK II BLIT": {"category": "cars", "age_limit": 6},
        "MARK II QUALIS": {"category": "cars", "age_limit": 6},
        "MARK II WAGON": {"category": "cars", "age_limit": 6},
        "MARK X": {"category": "cars", "age_limit": 6},
        "MARK X ZIO": {"category": "cars", "age_limit": 6},
        "MIRAI": {"category": "cars", "age_limit": 6},
        "MR-S": {"category": "cars", "age_limit": 6},
        "MR2": {"category": "cars", "age_limit": 6},
        "NADIA": {"category": "cars", "age_limit": 6},
        "NOAH": {"category": "cars", "age_limit": 6},
        "OPA": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "PASSO": {"category": "cars", "age_limit": 6},
        "PASSO SETTE": {"category": "cars", "age_limit": 6},
        "PIXIS EPOCH": {"category": "cars", "age_limit": 6},
        "PIXIS JOY": {"category": "cars", "age_limit": 6},
        "PIXIS MEGA": {"category": "cars", "age_limit": 6},
        "PIXIS SPACE": {"category": "cars", "age_limit": 6},
        "PIXIS TRUCK": {"category": "light_commercial", "age_limit": 6},
        "PIXIS VAN": {"category": "light_commercial", "age_limit": 10},
        "PLATZ": {"category": "cars", "age_limit": 6},
        "PORTE": {"category": "cars", "age_limit": 6},
        "PREMIO": {"category": "cars", "age_limit": 6},
        "PRIUS": {"category": "cars", "age_limit": 6},
        "PRIUS ALPHA": {"category": "cars", "age_limit": 6},
        "PRIUS PHV": {"category": "cars", "age_limit": 6},
        "PROBOX": {"category": "light_commercial", "age_limit": 10},
        "PROBOX WAGON": {"category": "cars", "age_limit": 6},
        "PROGRES": {"category": "cars", "age_limit": 6},
        "QUICK DELIVERY": {"category": "light_commercial", "age_limit": 10},
        "RACTIS": {"category": "cars", "age_limit": 6},
        "RAIZE": {"category": "cars", "age_limit": 6},
        "RAUM": {"category": "cars", "age_limit": 6},
        "RAV4": {"category": "cars", "age_limit": 6},
        "RAV4 L": {"category": "cars", "age_limit": 6},
        "REGIUS": {"category": "light_commercial", "age_limit": 10},
        "REGIUS ACE": {"category": "light_commercial", "age_limit": 10},
        "REGIUS VAN": {"category": "light_commercial", "age_limit": 10},
        "ROOMY": {"category": "cars", "age_limit": 6},
        "RUSH": {"category": "cars", "age_limit": 6},
        "SAI": {"category": "cars", "age_limit": 6},
        "SEQUOIA": {"category": "cars", "age_limit": 6},
        "SERA": {"category": "cars", "age_limit": 6},
        "SIENNA": {"category": "cars", "age_limit": 6},
        "SIENTA": {"category": "cars", "age_limit": 6},
        "SOARER": {"category": "cars", "age_limit": 6},
        "SPADE": {"category": "cars", "age_limit": 6},
        "SPARKY": {"category": "cars", "age_limit": 6},
        "SPORTS 800": {"category": "cars", "age_limit": 6},
        "SPRINTER": {"category": "cars", "age_limit": 6},
        "SPRINTER CARIB": {"category": "cars", "age_limit": 6},
        "SPRINTER CIELO": {"category": "cars", "age_limit": 6},
        "SPRINTER MARINO": {"category": "cars", "age_limit": 6},
        "SPRINTER TRUENO": {"category": "cars", "age_limit": 6},
        "SPRINTER VAN": {"category": "light_commercial", "age_limit": 10},
        "STARLET": {"category": "cars", "age_limit": 6},
        "SUCCEED VAN": {"category": "light_commercial", "age_limit": 10},
        "SUCCEED WAGON": {"category": "cars", "age_limit": 6},
        "SUPRA": {"category": "cars", "age_limit": 6},
        "TACOMA": {"category": "light_commercial", "age_limit": 6},
        "TANK": {"category": "cars", "age_limit": 6},
        "TERCEL": {"category": "cars", "age_limit": 6},
        "TOURING HIACE": {"category": "light_commercial", "age_limit": 10},
        "TOWN ACE": {"category": "light_commercial", "age_limit": 6},
        "TOWN ACE NOAH": {"category": "light_commercial", "age_limit": 10},
        "TOWN ACE TRUCK": {"category": "light_commercial", "age_limit": 6},
        "TOWN ACE VAN": {"category": "light_commercial", "age_limit": 10},
        "TOYOACE": {"category": "commercial", "age_limit": 20},
        "TOYOACE TRUCK": {"category": "commercial", "age_limit": 20},
        "TOYOACE VAN": {"category": "commercial", "age_limit": 20},
        "TUNDRA": {"category": "light_commercial", "age_limit": 10},
        "URBAN SUPPORTER": {"category": "light_commercial", "age_limit": 10},
        "VANGUARD": {"category": "cars", "age_limit": 6},
        "VELLFIRE": {"category": "cars", "age_limit": 6},
        "VELLFIRE HYBRID": {"category": "cars", "age_limit": 6},
        "VEROSSA": {"category": "cars", "age_limit": 6},
        "VISTA": {"category": "cars", "age_limit": 6},
        "VISTA ARDEO": {"category": "cars", "age_limit": 6},
        "VITZ": {"category": "cars", "age_limit": 6},
        "VOLTZ": {"category": "cars", "age_limit": 6},
        "VOXY": {"category": "cars", "age_limit": 6},
        "WILL CYPHA": {"category": "cars", "age_limit": 6},
        "WILL VI": {"category": "cars", "age_limit": 6},
        "WILL VS": {"category": "cars", "age_limit": 6},
        "WINDOM": {"category": "cars", "age_limit": 6},
        "WISH": {"category": "cars", "age_limit": 6},
        "YARIS": {"category": "cars", "age_limit": 6},
        "YARIS CROSS": {"category": "cars", "age_limit": 6}
    },
    "HONDA": {
        "ACCORD": {"category": "cars", "age_limit": 6},
        "ACCORD HYBRID": {"category": "cars", "age_limit": 6},
        "ACCORD INSPIRE": {"category": "cars", "age_limit": 6},
        "ACCORD TOURER": {"category": "cars", "age_limit": 6},
        "ACCORD WAGON": {"category": "cars", "age_limit": 6},
        "ACTY": {"category": "light_commercial", "age_limit": 6},
        "ACTY TRUCK": {"category": "light_commercial", "age_limit": 6},
        "ACTY VAN": {"category": "light_commercial", "age_limit": 10},
        "AIRWAVE": {"category": "cars", "age_limit": 6},
        "AMERICAN ACCORD": {"category": "cars", "age_limit": 6},
        "ASCOT": {"category": "cars", "age_limit": 6},
        "AVANCIER": {"category": "cars", "age_limit": 6},
        "BEAT": {"category": "cars", "age_limit": 6},
        "CITY": {"category": "cars", "age_limit": 6},
        "CIVIC": {"category": "cars", "age_limit": 6},
        "CIVIC COUPE": {"category": "cars", "age_limit": 6},
        "CIVIC FERIO": {"category": "cars", "age_limit": 6},
        "CIVIC HYBRID": {"category": "cars", "age_limit": 6},
        "CIVIC SHUTTLE": {"category": "cars", "age_limit": 6},
        "CLARITY PHEV": {"category": "cars", "age_limit": 6},
        "CR-V": {"category": "cars", "age_limit": 6},
        "CR-X": {"category": "cars", "age_limit": 6},
        "CR-X DELSOL": {"category": "cars", "age_limit": 6},
        "CR-Z": {"category": "cars", "age_limit": 6},
        "CROSSROAD": {"category": "cars", "age_limit": 6},
        "DOMANI": {"category": "cars", "age_limit": 6},
        "EDIX": {"category": "cars", "age_limit": 6},
        "ELEMENT": {"category": "cars", "age_limit": 6},
        "ELYSION": {"category": "cars", "age_limit": 6},
        "ELYSION PRESTIGE": {"category": "cars", "age_limit": 6},
        "FIT": {"category": "cars", "age_limit": 6},
        "FIT HYBRID": {"category": "cars", "age_limit": 6},
        "FIT SHUTTLE": {"category": "cars", "age_limit": 6},
        "FIT SHUTTLE HYBRID": {"category": "cars", "age_limit": 6},
        "FREED": {"category": "cars", "age_limit": 6},
        "FREED + HYBRID": {"category": "cars", "age_limit": 6},
        "FREED HYBRID": {"category": "cars", "age_limit": 6},
        "FREED SPIKE": {"category": "cars", "age_limit": 6},
        "FREED SPIKE HYBRID": {"category": "cars", "age_limit": 6},
        "FREED+": {"category": "cars", "age_limit": 6},
        "GRACE": {"category": "cars", "age_limit": 6},
        "HONDA E": {"category": "cars", "age_limit": 6},
        "HR-V": {"category": "cars", "age_limit": 6},
        "INSIGHT": {"category": "cars", "age_limit": 6},
        "INSIGHT EXCLUSIVE": {"category": "cars", "age_limit": 6},
        "INSPIRE": {"category": "cars", "age_limit": 6},
        "INTEGRA": {"category": "cars", "age_limit": 6},
        "JADE": {"category": "cars", "age_limit": 6},
        "LAGREAT": {"category": "cars", "age_limit": 6},
        "LEGEND": {"category": "cars", "age_limit": 6},
        "LIFE": {"category": "cars", "age_limit": 6},
        "LIFE DUNK": {"category": "cars", "age_limit": 6},
        "LIVE DIVA": {"category": "cars", "age_limit": 6},
        "LOGO": {"category": "cars", "age_limit": 6},
        "MDX": {"category": "cars", "age_limit": 6},
        "MOBILIO": {"category": "cars", "age_limit": 6},
        "MOBILIO SPIKE": {"category": "cars", "age_limit": 6},
        "N BOX": {"category": "cars", "age_limit": 6},
        "N BOX +": {"category": "cars", "age_limit": 6},
        "N BOX CUSTOM": {"category": "cars", "age_limit": 6},
        "N BOX+CUSTOM": {"category": "cars", "age_limit": 6},
        "N-BOX SLASH": {"category": "cars", "age_limit": 6},
        "N-ONE": {"category": "cars", "age_limit": 6},
        "N-VAN": {"category": "light_commercial", "age_limit": 10},
        "N-VAN E:": {"category": "light_commercial", "age_limit": 10},
        "N-WGN": {"category": "cars", "age_limit": 6},
        "N360": {"category": "cars", "age_limit": 6},
        "NSX": {"category": "cars", "age_limit": 6},
        "ODYSSEY": {"category": "cars", "age_limit": 6},
        "ODYSSEY HYBRID": {"category": "cars", "age_limit": 6},
        "ODYSSEY PRESTIGE": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "PARTNER": {"category": "light_commercial", "age_limit": 10},
        "PRELUDE": {"category": "cars", "age_limit": 6},
        "S-MX": {"category": "cars", "age_limit": 6},
        "S2000": {"category": "cars", "age_limit": 6},
        "S600": {"category": "cars", "age_limit": 6},
        "S660": {"category": "cars", "age_limit": 6},
        "SHUTTLE": {"category": "cars", "age_limit": 6},
        "STEPWGN": {"category": "cars", "age_limit": 6},
        "STEPWGN SPADA": {"category": "cars", "age_limit": 6},
        "STREAM": {"category": "cars", "age_limit": 6},
        "STREET": {"category": "cars", "age_limit": 6},
        "THATS": {"category": "cars", "age_limit": 6},
        "TODAY": {"category": "cars", "age_limit": 6},
        "TORNEO": {"category": "cars", "age_limit": 6},
        "VAMOS": {"category": "light_commercial", "age_limit": 6},
        "VAMOS HOBIO": {"category": "light_commercial", "age_limit": 6},
        "VEZEL": {"category": "cars", "age_limit": 6},
        "WR-V": {"category": "cars", "age_limit": 6},
        "Z": {"category": "cars", "age_limit": 6},
        "ZEST": {"category": "cars", "age_limit": 6},
        "ZEST SPARK": {"category": "cars", "age_limit": 6},
        "ZR-V": {"category": "cars", "age_limit": 6}
    },
    "NISSAN": {
        "180SX": {"category": "cars", "age_limit": 6},
        "AD": {"category": "light_commercial", "age_limit": 10},
        "AD EXPERT": {"category": "light_commercial", "age_limit": 10},
        "AD MAX WAGON": {"category": "cars", "age_limit": 6},
        "AD VAN": {"category": "light_commercial", "age_limit": 10},
        "ARIYA": {"category": "cars", "age_limit": 6},
        "ATLAS": {"category": "commercial", "age_limit": 20},
        "ATLAS DUMP": {"category": "commercial", "age_limit": 25},
        "ATLAS LOCO": {"category": "commercial", "age_limit": 20},
        "AURA": {"category": "cars", "age_limit": 6},
        "BASSARA": {"category": "cars", "age_limit": 6},
        "BE-1": {"category": "cars", "age_limit": 6},
        "BIG THUMB": {"category": "heavy_duty", "age_limit": 30},
        "BLUEBIRD": {"category": "cars", "age_limit": 6},
        "BLUEBIRD SYLPHY": {"category": "cars", "age_limit": 6},
        "CARAVAN": {"category": "light_commercial", "age_limit": 10},
        "CARAVAN BUS": {"category": "light_commercial", "age_limit": 10},
        "CARAVAN COACH": {"category": "light_commercial", "age_limit": 10},
        "CARAVAN WAGON": {"category": "cars", "age_limit": 6},
        "CEDRIC": {"category": "cars", "age_limit": 6},
        "CEDRIC VAN": {"category": "light_commercial", "age_limit": 10},
        "CEDRIC WAGON": {"category": "cars", "age_limit": 6},
        "CEFIRO": {"category": "cars", "age_limit": 6},
        "CIMA": {"category": "cars", "age_limit": 6},
        "CIVILIAN": {"category": "commercial", "age_limit": 15},
        "CLIPPER": {"category": "light_commercial", "age_limit": 6},
        "CLIPPER RIO": {"category": "light_commercial", "age_limit": 6},
        "CLIPPER TRUCK": {"category": "light_commercial", "age_limit": 6},
        "CLIPPER VAN": {"category": "light_commercial", "age_limit": 10},
        "CONDOR": {"category": "commercial", "age_limit": 25},
        "CUBE": {"category": "cars", "age_limit": 6},
        "CUBE CUBIC": {"category": "cars", "age_limit": 6},
        "DATSUN": {"category": "cars", "age_limit": 6},
        "DAYZ": {"category": "cars", "age_limit": 6},
        "DAYZ ROOX": {"category": "cars", "age_limit": 6},
        "DUALIS": {"category": "cars", "age_limit": 6},
        "E-NV200 VAN": {"category": "light_commercial", "age_limit": 10},
        "E-NV200 WAGON": {"category": "light_commercial", "age_limit": 10},
        "ELGRAND": {"category": "cars", "age_limit": 6},
        "FAIRLADY Z": {"category": "cars", "age_limit": 6},
        "FIGARO": {"category": "cars", "age_limit": 6},
        "FRONTIER": {"category": "light_commercial", "age_limit": 6},
        "FUGA": {"category": "cars", "age_limit": 6},
        "FUGA HYBRID": {"category": "cars", "age_limit": 6},
        "GLORIA": {"category": "cars", "age_limit": 6},
        "GLORIA VAN": {"category": "light_commercial", "age_limit": 10},
        "GLORIA WAGON": {"category": "cars", "age_limit": 6},
        "GT-R": {"category": "cars", "age_limit": 6},
        "HOMY COACH": {"category": "light_commercial", "age_limit": 10},
        "HOMY ELGRAND": {"category": "cars", "age_limit": 6},
        "INFINITI Q45": {"category": "cars", "age_limit": 6},
        "JUKE": {"category": "cars", "age_limit": 6},
        "KICKS": {"category": "cars", "age_limit": 6},
        "LAFESTA": {"category": "cars", "age_limit": 6},
        "LARGO": {"category": "cars", "age_limit": 6},
        "LAUREL": {"category": "cars", "age_limit": 6},
        "LEAF": {"category": "cars", "age_limit": 6},
        "LEOPARD": {"category": "cars", "age_limit": 6},
        "LIBERTY": {"category": "cars", "age_limit": 6},
        "MARCH": {"category": "cars", "age_limit": 6},
        "MICRA": {"category": "cars", "age_limit": 6},
        "MICRA C+C": {"category": "cars", "age_limit": 6},
        "MISTRAL": {"category": "cars", "age_limit": 6},
        "MOCO": {"category": "cars", "age_limit": 6},
        "MURANO": {"category": "cars", "age_limit": 6},
        "NOTE": {"category": "cars", "age_limit": 6},
        "NT100 CLIPPER": {"category": "light_commercial", "age_limit": 6},
        "NT450 ATLAS": {"category": "commercial", "age_limit": 20},
        "NV100 CLIPPER": {"category": "light_commercial", "age_limit": 6},
        "NV100 CLIPPER RIO": {"category": "light_commercial", "age_limit": 6},
        "NV150 AD": {"category": "light_commercial", "age_limit": 10},
        "NV200 VANETTE": {"category": "light_commercial", "age_limit": 10},
        "NV200 VANETTE VAN": {"category": "light_commercial", "age_limit": 10},
        "NV350 CARAVAN": {"category": "light_commercial", "age_limit": 10},
        "NV350 CARAVAN WAGON": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "OTTI": {"category": "cars", "age_limit": 6},
        "PAO": {"category": "cars", "age_limit": 6},
        "PINO": {"category": "cars", "age_limit": 6},
        "PRAIRIE JOY": {"category": "cars", "age_limit": 6},
        "PRESAGE": {"category": "cars", "age_limit": 6},
        "PRESIDENT": {"category": "cars", "age_limit": 6},
        "PRESIDENT JS": {"category": "cars", "age_limit": 6},
        "PRIMERA": {"category": "cars", "age_limit": 6},
        "PRIMERA CAMINO": {"category": "cars", "age_limit": 6},
        "PRIMERA CAMINO WAGON": {"category": "cars", "age_limit": 6},
        "PRIMERA WAGON": {"category": "cars", "age_limit": 6},
        "PRINCE GLORIA": {"category": "cars", "age_limit": 6},
        "PULSAR": {"category": "cars", "age_limit": 6},
        "PULSAR SERIE": {"category": "cars", "age_limit": 6},
        "PULSAR SERIE S-RV": {"category": "cars", "age_limit": 6},
        "QUEST": {"category": "cars", "age_limit": 6},
        "RASHEEN": {"category": "cars", "age_limit": 6},
        "ROOX": {"category": "cars", "age_limit": 6},
        "S-CARGO": {"category": "light_commercial", "age_limit": 10},
        "SAFARI": {"category": "cars", "age_limit": 6},
        "SAKURA": {"category": "cars", "age_limit": 6},
        "SERENA": {"category": "cars", "age_limit": 6},
        "SILVIA": {"category": "cars", "age_limit": 6},
        "SKYLINE": {"category": "cars", "age_limit": 6},
        "SKYLINE CROSSOVER": {"category": "cars", "age_limit": 6},
        "STAGEA": {"category": "cars", "age_limit": 6},
        "SUNNY": {"category": "cars", "age_limit": 6},
        "SUNNY NX COUPE": {"category": "cars", "age_limit": 6},
        "SUNNY TRUCK": {"category": "light_commercial", "age_limit": 6},
        "TEANA": {"category": "cars", "age_limit": 6},
        "TERRANO": {"category": "cars", "age_limit": 6},
        "TERRANO REGULUS": {"category": "cars", "age_limit": 6},
        "TIIDA": {"category": "cars", "age_limit": 6},
        "TIIDA LATIO": {"category": "cars", "age_limit": 6},
        "UD": {"category": "commercial", "age_limit": 25},
        "VANETTE": {"category": "light_commercial", "age_limit": 10},
        "VANETTE TRUCK": {"category": "light_commercial", "age_limit": 6},
        "VANETTE VAN": {"category": "light_commercial", "age_limit": 10},
        "WINGROAD": {"category": "cars", "age_limit": 6},
        "X-TRAIL": {"category": "cars", "age_limit": 6}
    },
    "MAZDA": {
        "ATENZA": {"category": "cars", "age_limit": 6},
        "ATENZA SEDAN": {"category": "cars", "age_limit": 6},
        "ATENZA SPORT": {"category": "cars", "age_limit": 6},
        "ATENZA SPORT WAGON": {"category": "cars", "age_limit": 6},
        "ATENZA WAGON": {"category": "cars", "age_limit": 6},
        "AUTOZAM AZ-1": {"category": "cars", "age_limit": 6},
        "AUTOZAM CAROL": {"category": "cars", "age_limit": 6},
        "AUTOZAM SCRUM": {"category": "light_commercial", "age_limit": 6},
        "AXELA": {"category": "cars", "age_limit": 6},
        "AXELA HYBRID": {"category": "cars", "age_limit": 6},
        "AXELA SPORT": {"category": "cars", "age_limit": 6},
        "AZ OFFROAD": {"category": "cars", "age_limit": 6},
        "AZ WAGON": {"category": "cars", "age_limit": 6},
        "AZ WAGON CUSTOM STYLE": {"category": "cars", "age_limit": 6},
        "BIANTE": {"category": "cars", "age_limit": 6},
        "BONGO": {"category": "light_commercial", "age_limit": 10},
        "BONGO BRAWNY TRUCK": {"category": "light_commercial", "age_limit": 10},
        "BONGO BRAWNY VAN": {"category": "light_commercial", "age_limit": 10},
        "BONGO FRIENDEE": {"category": "cars", "age_limit": 6},
        "BONGO TRUCK": {"category": "light_commercial", "age_limit": 6},
        "BONGO VAN": {"category": "light_commercial", "age_limit": 10},
        "BONGO WAGON": {"category": "cars", "age_limit": 6},
        "CAPELLA WAGON": {"category": "cars", "age_limit": 6},
        "CAROL": {"category": "cars", "age_limit": 6},
        "CAROL ECO": {"category": "cars", "age_limit": 6},
        "COSMO SPORT": {"category": "cars", "age_limit": 6},
        "CX-3": {"category": "cars", "age_limit": 6},
        "CX-30": {"category": "cars", "age_limit": 6},
        "CX-5": {"category": "cars", "age_limit": 6},
        "CX-60": {"category": "cars", "age_limit": 6},
        "CX-7": {"category": "cars", "age_limit": 6},
        "CX-8": {"category": "cars", "age_limit": 6},
        "CX-80": {"category": "cars", "age_limit": 6},
        "DEMIO": {"category": "cars", "age_limit": 6},
        "EFINI RX-7": {"category": "cars", "age_limit": 6},
        "EUNOS": {"category": "cars", "age_limit": 6},
        "EUNOS COSMO": {"category": "cars", "age_limit": 6},
        "EUNOS ROADSTER": {"category": "cars", "age_limit": 6},
        "FAMILIA": {"category": "cars", "age_limit": 6},
        "FAMILIA ASTINA": {"category": "cars", "age_limit": 6},
        "FAMILIA S-WAGON": {"category": "cars", "age_limit": 6},
        "FAMILIA VAN": {"category": "light_commercial", "age_limit": 10},
        "FAMILIA WAGON": {"category": "cars", "age_limit": 6},
        "FLAIR": {"category": "cars", "age_limit": 6},
        "FLAIR CROSSOVER": {"category": "cars", "age_limit": 6},
        "FLAIR WAGON": {"category": "cars", "age_limit": 6},
        "FLAIR WAGON CUSTOM STYLE": {"category": "cars", "age_limit": 6},
        "FLAIR WAGON TOUGH STYLE": {"category": "cars", "age_limit": 6},
        "LANTIS": {"category": "cars", "age_limit": 6},
        "LAPUTA": {"category": "cars", "age_limit": 6},
        "LUCE": {"category": "cars", "age_limit": 6},
        "MAZDA SPEED ATENZA": {"category": "cars", "age_limit": 6},
        "MAZDA SPEED AXELA": {"category": "cars", "age_limit": 6},
        "MAZDA2": {"category": "cars", "age_limit": 6},
        "MAZDA3": {"category": "cars", "age_limit": 6},
        "MAZDA3 FASTBACK": {"category": "cars", "age_limit": 6},
        "MAZDA6": {"category": "cars", "age_limit": 6},
        "MILLENIA": {"category": "cars", "age_limit": 6},
        "MPV": {"category": "cars", "age_limit": 6},
        "MX-30": {"category": "cars", "age_limit": 6},
        "MX-30 EV MODEL": {"category": "cars", "age_limit": 6},
        "MX-30 ROTARY-EV": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "PORTER CAB": {"category": "light_commercial", "age_limit": 6},
        "PREMACY": {"category": "cars", "age_limit": 6},
        "PROCEED": {"category": "cars", "age_limit": 6},
        "PROCEED MARVIE": {"category": "cars", "age_limit": 6},
        "ROADSTER": {"category": "cars", "age_limit": 6},
        "ROADSTER RF": {"category": "cars", "age_limit": 6},
        "RX-7": {"category": "cars", "age_limit": 6},
        "RX-8": {"category": "cars", "age_limit": 6},
        "SAVANNA RX-7": {"category": "cars", "age_limit": 6},
        "SCRUM": {"category": "light_commercial", "age_limit": 6},
        "SCRUM TRUCK": {"category": "light_commercial", "age_limit": 6},
        "SCRUM WAGON": {"category": "cars", "age_limit": 6},
        "SENTIA": {"category": "cars", "age_limit": 6},
        "SPIANO": {"category": "cars", "age_limit": 6},
        "TITAN": {"category": "commercial", "age_limit": 20},
        "TITAN DASH": {"category": "light_commercial", "age_limit": 6},
        "TITAN TRUCK": {"category": "commercial", "age_limit": 20},
        "TRIBUTE": {"category": "cars", "age_limit": 6},
        "VERISA": {"category": "cars", "age_limit": 6}
    },
    "MITSUBISHI": {
        "AIRTREK": {"category": "cars", "age_limit": 6},
        "BRAVO": {"category": "cars", "age_limit": 6},
        "CANTER": {"category": "commercial", "age_limit": 20},
        "CANTER DUMP": {"category": "commercial", "age_limit": 25},
        "CHALLENGER": {"category": "cars", "age_limit": 6},
        "COLT": {"category": "cars", "age_limit": 6},
        "COLT PLUS": {"category": "cars", "age_limit": 6},
        "DEBONAIR": {"category": "cars", "age_limit": 6},
        "DELICA CARGO": {"category": "light_commercial", "age_limit": 10},
        "DELICA D:2": {"category": "cars", "age_limit": 6},
        "DELICA D:3": {"category": "cars", "age_limit": 6},
        "DELICA D:5": {"category": "cars", "age_limit": 6},
        "DELICA MINI": {"category": "cars", "age_limit": 6},
        "DELICA SPACE GEAR": {"category": "cars", "age_limit": 6},
        "DELICA TRUCK": {"category": "light_commercial", "age_limit": 6},
        "DELICA VAN": {"category": "light_commercial", "age_limit": 10},
        "DELICA WAGON": {"category": "cars", "age_limit": 6},
        "DIAMANTE": {"category": "cars", "age_limit": 6},
        "DINGO": {"category": "cars", "age_limit": 6},
        "ECLIPSE": {"category": "cars", "age_limit": 6},
        "ECLIPSE CROSS": {"category": "cars", "age_limit": 6},
        "ECLIPSE CROSS PHEV": {"category": "cars", "age_limit": 6},
        "ECLIPSE SPIDER": {"category": "cars", "age_limit": 6},
        "EK ACTIVE": {"category": "cars", "age_limit": 6},
        "EK CLASSY": {"category": "cars", "age_limit": 6},
        "EK CUSTOM": {"category": "cars", "age_limit": 6},
        "EK SPACE": {"category": "cars", "age_limit": 6},
        "EK SPACE CUSTOM": {"category": "cars", "age_limit": 6},
        "EK SPORTS": {"category": "cars", "age_limit": 6},
        "EK WAGON": {"category": "cars", "age_limit": 6},
        "EK X": {"category": "cars", "age_limit": 6},
        "EK X EV": {"category": "cars", "age_limit": 6},
        "EK X SPACE": {"category": "cars", "age_limit": 6},
        "FORKLIFT": {"category": "heavy_duty", "age_limit": 30},
        "FTO": {"category": "cars", "age_limit": 6},
        "FUSO": {"category": "commercial", "age_limit": 25},
        "FUSO AERO MIDI": {"category": "commercial", "age_limit": 15},
        "FUSO CANTER GUTS": {"category": "commercial", "age_limit": 20},
        "FUSO FIGHTER": {"category": "commercial", "age_limit": 25},
        "FUSO ROSA": {"category": "commercial", "age_limit": 15},
        "FUSO SUPER GREAT": {"category": "commercial", "age_limit": 30},
        "FUSO THE GREAT": {"category": "commercial", "age_limit": 30},
        "FUSO TRUCK": {"category": "commercial", "age_limit": 25},
        "GALANT": {"category": "cars", "age_limit": 6},
        "GALANT FORTIS": {"category": "cars", "age_limit": 6},
        "GALANT FORTIS SPORTBACK": {"category": "cars", "age_limit": 6},
        "GRANDIS": {"category": "cars", "age_limit": 6},
        "GTO": {"category": "cars", "age_limit": 6},
        "I": {"category": "cars", "age_limit": 6},
        "I-MIEV": {"category": "cars", "age_limit": 6},
        "JEEP": {"category": "cars", "age_limit": 6},
        "LANCER": {"category": "cars", "age_limit": 6},
        "LANCER CARGO": {"category": "light_commercial", "age_limit": 10},
        "LANCER CEDIA": {"category": "cars", "age_limit": 6},
        "LANCER EVOLUTION": {"category": "cars", "age_limit": 6},
        "LANCER WAGON": {"category": "cars", "age_limit": 6},
        "LEGNUM": {"category": "cars", "age_limit": 6},
        "LIBERO": {"category": "light_commercial", "age_limit": 10},
        "MINICA": {"category": "cars", "age_limit": 6},
        "MINICA TOPPO": {"category": "cars", "age_limit": 6},
        "MINICAB": {"category": "light_commercial", "age_limit": 6},
        "MINICAB MIEV": {"category": "light_commercial", "age_limit": 6},
        "MINICAB MIEV TRUCK": {"category": "light_commercial", "age_limit": 6},
        "MINICAB TRUCK": {"category": "light_commercial", "age_limit": 6},
        "MIRAGE": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "OUTLANDER": {"category": "cars", "age_limit": 6},
        "OUTLANDER PHEV": {"category": "cars", "age_limit": 6},
        "PAJERO": {"category": "cars", "age_limit": 6},
        "PAJERO IO": {"category": "cars", "age_limit": 6},
        "PAJERO JUNIOR": {"category": "cars", "age_limit": 6},
        "PAJERO MINI": {"category": "cars", "age_limit": 6},
        "PROUDIA": {"category": "cars", "age_limit": 6},
        "RVR": {"category": "cars", "age_limit": 6},
        "TOPPO": {"category": "cars", "age_limit": 6},
        "TOPPO BJ": {"category": "cars", "age_limit": 6},
        "TOWN BOX": {"category": "cars", "age_limit": 6},
        "TRITON": {"category": "light_commercial", "age_limit": 6}
    },
    "SUBARU": {
        "360": {"category": "cars", "age_limit": 6},
        "ALCYONE SVX": {"category": "cars", "age_limit": 6},
        "BRZ": {"category": "cars", "age_limit": 6},
        "CHIFFON": {"category": "cars", "age_limit": 6},
        "CROSSTREK": {"category": "cars", "age_limit": 6},
        "DEX": {"category": "cars", "age_limit": 6},
        "DIAS WAGON": {"category": "cars", "age_limit": 6},
        "EXIGA": {"category": "cars", "age_limit": 6},
        "EXIGA CROSSOVER 7": {"category": "cars", "age_limit": 6},
        "FORESTER": {"category": "cars", "age_limit": 6},
        "IMPREZA": {"category": "cars", "age_limit": 6},
        "IMPREZA ANESIS": {"category": "cars", "age_limit": 6},
        "IMPREZA G4": {"category": "cars", "age_limit": 6},
        "IMPREZA SPORT": {"category": "cars", "age_limit": 6},
        "IMPREZA SPORT HYBRID": {"category": "cars", "age_limit": 6},
        "IMPREZA SPORT WAGON": {"category": "cars", "age_limit": 6},
        "IMPREZA WRX": {"category": "cars", "age_limit": 6},
        "IMPREZA XV": {"category": "cars", "age_limit": 6},
        "JUSTY": {"category": "cars", "age_limit": 6},
        "LEGACY": {"category": "cars", "age_limit": 6},
        "LEGACY B4": {"category": "cars", "age_limit": 6},
        "LEGACY LANCASTER": {"category": "cars", "age_limit": 6},
        "LEGACY TOURING WAGON": {"category": "cars", "age_limit": 6},
        "LEGACY WAGON": {"category": "cars", "age_limit": 6},
        "LEONE": {"category": "cars", "age_limit": 6},
        "LEVORG": {"category": "cars", "age_limit": 6},
        "LEVORG LAYBAC": {"category": "cars", "age_limit": 6},
        "LUCRA": {"category": "cars", "age_limit": 6},
        "LUCRA CUSTOM": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "OUTBACK": {"category": "cars", "age_limit": 6},
        "PLEO": {"category": "cars", "age_limit": 6},
        "PLEO CUSTOM": {"category": "cars", "age_limit": 6},
        "PLEO NESTA": {"category": "cars", "age_limit": 6},
        "PLEO PLUS": {"category": "cars", "age_limit": 6},
        "R1": {"category": "cars", "age_limit": 6},
        "R2": {"category": "cars", "age_limit": 6},
        "REX": {"category": "cars", "age_limit": 6},
        "SAMBAR": {"category": "light_commercial", "age_limit": 6},
        "SAMBAR DIAS": {"category": "cars", "age_limit": 6},
        "SAMBAR TRUCK": {"category": "light_commercial", "age_limit": 6},
        "SAMBAR VAN": {"category": "light_commercial", "age_limit": 10},
        "SOLTERRA": {"category": "cars", "age_limit": 6},
        "STELLA": {"category": "cars", "age_limit": 6},
        "SUBARU XV": {"category": "cars", "age_limit": 6},
        "TREZIA": {"category": "cars", "age_limit": 6},
        "VIVIO": {"category": "cars", "age_limit": 6},
        "VIVIO BISTRO": {"category": "cars", "age_limit": 6},
        "WRX S4": {"category": "cars", "age_limit": 6},
        "WRX STI": {"category": "cars", "age_limit": 6}
    },
    "SUZUKI": {
        "AERIO": {"category": "cars", "age_limit": 6},
        "ALTO": {"category": "cars", "age_limit": 6},
        "ALTO ECO": {"category": "cars", "age_limit": 6},
        "ALTO LAPIN": {"category": "cars", "age_limit": 6},
        "ALTO LAPIN CHOCOLATE": {"category": "cars", "age_limit": 6},
        "ALTO TURBO RS": {"category": "cars", "age_limit": 6},
        "ALTO WORKS": {"category": "cars", "age_limit": 6},
        "BALENO": {"category": "cars", "age_limit": 6},
        "CAPPUCCINO": {"category": "cars", "age_limit": 6},
        "CARA": {"category": "cars", "age_limit": 6},
        "CARRY": {"category": "light_commercial", "age_limit": 6},
        "CARRY TRUCK": {"category": "light_commercial", "age_limit": 6},
        "CERVO": {"category": "cars", "age_limit": 6},
        "CERVO CLASSIC": {"category": "cars", "age_limit": 6},
        "CERVO MODE": {"category": "cars", "age_limit": 6},
        "CRUZE": {"category": "cars", "age_limit": 6},
        "CULTUS ESTEEM": {"category": "cars", "age_limit": 6},
        "ESCUDO": {"category": "cars", "age_limit": 6},
        "EVERY": {"category": "light_commercial", "age_limit": 6},
        "EVERY LANDY": {"category": "light_commercial", "age_limit": 6},
        "EVERY VAN": {"category": "light_commercial", "age_limit": 10},
        "EVERY WAGON": {"category": "cars", "age_limit": 6},
        "FRONTE": {"category": "cars", "age_limit": 6},
        "FRONX": {"category": "cars", "age_limit": 6},
        "HUSTLER": {"category": "cars", "age_limit": 6},
        "IGNIS": {"category": "cars", "age_limit": 6},
        "JIMNY": {"category": "cars", "age_limit": 6},
        "JIMNY NOMADE": {"category": "cars", "age_limit": 6},
        "JIMNY SIERRA": {"category": "cars", "age_limit": 6},
        "JIMNY WIDE": {"category": "cars", "age_limit": 6},
        "KEI": {"category": "cars", "age_limit": 6},
        "KEI WORKS": {"category": "cars", "age_limit": 6},
        "KIZASHI": {"category": "cars", "age_limit": 6},
        "LANDY": {"category": "cars", "age_limit": 6},
        "LAPIN LC": {"category": "cars", "age_limit": 6},
        "MIGHTY BOY": {"category": "light_commercial", "age_limit": 6},
        "MRWAGON": {"category": "cars", "age_limit": 6},
        "MW": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "PALETTE": {"category": "cars", "age_limit": 6},
        "PALETTE SW": {"category": "cars", "age_limit": 6},
        "SOLIO": {"category": "cars", "age_limit": 6},
        "SOLIO BANDIT": {"category": "cars", "age_limit": 6},
        "SPACIA": {"category": "cars", "age_limit": 6},
        "SPACIA BACE": {"category": "cars", "age_limit": 6},
        "SPACIA CUSTOM": {"category": "cars", "age_limit": 6},
        "SPACIA GEAR": {"category": "cars", "age_limit": 6},
        "SPLASH": {"category": "cars", "age_limit": 6},
        "SWIFT": {"category": "cars", "age_limit": 6},
        "SWIFT SPORTS": {"category": "cars", "age_limit": 6},
        "SX4": {"category": "cars", "age_limit": 6},
        "SX4 S-CROSS": {"category": "cars", "age_limit": 6},
        "SX4 SEDAN": {"category": "cars", "age_limit": 6},
        "TWIN": {"category": "cars", "age_limit": 6},
        "WAGON R": {"category": "cars", "age_limit": 6},
        "WAGON R CUSTOM Z": {"category": "cars", "age_limit": 6},
        "WAGON R RR": {"category": "cars", "age_limit": 6},
        "WAGON R SMILE": {"category": "cars", "age_limit": 6},
        "WAGON R SOLIO": {"category": "cars", "age_limit": 6},
        "WAGON R STINGRAY": {"category": "cars", "age_limit": 6},
        "XBEE": {"category": "cars", "age_limit": 6}
    },
    "DAIHATSU": {
        "ALTIS": {"category": "cars", "age_limit": 6},
        "ATRAI": {"category": "light_commercial", "age_limit": 6},
        "ATRAI 7": {"category": "cars", "age_limit": 6},
        "ATRAI VAN": {"category": "light_commercial", "age_limit": 10},
        "ATRAI WAGON": {"category": "cars", "age_limit": 6},
        "BE GO": {"category": "cars", "age_limit": 6},
        "BOON": {"category": "cars", "age_limit": 6},
        "CAST": {"category": "cars", "age_limit": 6},
        "CAST ACTIVA": {"category": "cars", "age_limit": 6},
        "CHARADE": {"category": "cars", "age_limit": 6},
        "COO": {"category": "cars", "age_limit": 6},
        "COPEN": {"category": "cars", "age_limit": 6},
        "DELTA TRUCK": {"category": "light_commercial", "age_limit": 6},
        "ESSE": {"category": "cars", "age_limit": 6},
        "GRAN MAX": {"category": "light_commercial", "age_limit": 10},
        "HIJET": {"category": "light_commercial", "age_limit": 6},
        "HIJET CARGO": {"category": "light_commercial", "age_limit": 10},
        "HIJET OP_DECK VAN": {"category": "light_commercial", "age_limit": 10},
        "HIJET TRUCK": {"category": "light_commercial", "age_limit": 6},
        "HIJET VAN": {"category": "light_commercial", "age_limit": 10},
        "HIJET СADDY": {"category": "light_commercial", "age_limit": 6},
        "MAX": {"category": "cars", "age_limit": 6},
        "MEBIUS": {"category": "cars", "age_limit": 6},
        "MIDGET II": {"category": "light_commercial", "age_limit": 6},
        "MIDGET II CARGO": {"category": "light_commercial", "age_limit": 10},
        "MIRA": {"category": "cars", "age_limit": 6},
        "MIRA AVY": {"category": "cars", "age_limit": 6},
        "MIRA COCOA": {"category": "cars", "age_limit": 6},
        "MIRA CUSTOM": {"category": "cars", "age_limit": 6},
        "MIRA E:S": {"category": "cars", "age_limit": 6},
        "MIRA GINO": {"category": "cars", "age_limit": 6},
        "MIRA GINO 1000": {"category": "cars", "age_limit": 6},
        "MIRA TOCOT": {"category": "cars", "age_limit": 6},
        "MIRA TR-XX": {"category": "cars", "age_limit": 6},
        "MOVE": {"category": "cars", "age_limit": 6},
        "MOVE CANBUS": {"category": "cars", "age_limit": 6},
        "MOVE CONTE": {"category": "cars", "age_limit": 6},
        "MOVE LATTE": {"category": "cars", "age_limit": 6},
        "NAKED": {"category": "cars", "age_limit": 6},
        "OPTI": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "ROCKY": {"category": "cars", "age_limit": 6},
        "SONICA": {"category": "cars", "age_limit": 6},
        "TAFT": {"category": "cars", "age_limit": 6},
        "TANTO": {"category": "cars", "age_limit": 6},
        "TANTO EXE": {"category": "cars", "age_limit": 6},
        "TANTO FUN CROSS": {"category": "cars", "age_limit": 6},
        "TERIOS": {"category": "cars", "age_limit": 6},
        "TERIOS KID": {"category": "cars", "age_limit": 6},
        "THOR": {"category": "cars", "age_limit": 6},
        "WAKE": {"category": "cars", "age_limit": 6}
    },
    "ISUZU": {
        "117COUPE": {"category": "cars", "age_limit": 6},
        "ASKA": {"category": "cars", "age_limit": 6},
        "BELLETT": {"category": "cars", "age_limit": 6},
        "BIGHORN": {"category": "cars", "age_limit": 6},
        "COMO": {"category": "light_commercial", "age_limit": 10},
        "ELF": {"category": "commercial", "age_limit": 20},
        "ELF DUMP": {"category": "commercial", "age_limit": 25},
        "FARGO TRUCK": {"category": "light_commercial", "age_limit": 10},
        "FORWARD": {"category": "commercial", "age_limit": 25},
        "FORWARD DUMP": {"category": "commercial", "age_limit": 25},
        "FORWARD JUSTON": {"category": "commercial", "age_limit": 25},
        "GALA": {"category": "commercial", "age_limit": 15},
        "GALA MIO": {"category": "commercial", "age_limit": 15},
        "GEMINI": {"category": "cars", "age_limit": 6},
        "GIGA": {"category": "commercial", "age_limit": 30},
        "GIGA MAX": {"category": "commercial", "age_limit": 30},
        "JOURNEY": {"category": "commercial", "age_limit": 15},
        "JOURNEY BUS": {"category": "commercial", "age_limit": 15},
        "MU": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "PIAZZA": {"category": "cars", "age_limit": 6},
        "RODEO": {"category": "light_commercial", "age_limit": 6},
        "VEHICROSS": {"category": "cars", "age_limit": 6},
        "WIZARD": {"category": "cars", "age_limit": 6}
    },
    "LEXUS": {
        "CT": {"category": "cars", "age_limit": 6},
        "ES": {"category": "cars", "age_limit": 6},
        "GS": {"category": "cars", "age_limit": 6},
        "GS F": {"category": "cars", "age_limit": 6},
        "GS200T": {"category": "cars", "age_limit": 6},
        "GX": {"category": "cars", "age_limit": 6},
        "HS": {"category": "cars", "age_limit": 6},
        "IS": {"category": "cars", "age_limit": 6},
        "IS F": {"category": "cars", "age_limit": 6},
        "LBX": {"category": "cars", "age_limit": 6},
        "LC": {"category": "cars", "age_limit": 6},
        "LM": {"category": "cars", "age_limit": 6},
        "LS": {"category": "cars", "age_limit": 6},
        "LX": {"category": "cars", "age_limit": 6},
        "NX": {"category": "cars", "age_limit": 6},
        "RC": {"category": "cars", "age_limit": 6},
        "RC F": {"category": "cars", "age_limit": 6},
        "RX": {"category": "cars", "age_limit": 6},
        "RZ": {"category": "cars", "age_limit": 6},
        "SC": {"category": "cars", "age_limit": 6},
        "UX": {"category": "cars", "age_limit": 6}
    },
    "ACURA": {
        "TL": {"category": "cars", "age_limit": 6}
    },
    "HINO": {
        "DUTRO": {"category": "commercial", "age_limit": 20},
        "DUTRO TRUCK": {"category": "commercial", "age_limit": 20},
        "LIESSE": {"category": "commercial", "age_limit": 15},
        "LIESSE II": {"category": "commercial", "age_limit": 15},
        "MELPHA": {"category": "commercial", "age_limit": 15},
        "OTHER": {"category": "commercial", "age_limit": 20},
        "PONCHO": {"category": "commercial", "age_limit": 15},
        "PROFIA": {"category": "commercial", "age_limit": 30},
        "RAINBOW": {"category": "commercial", "age_limit": 15},
        "RANGER": {"category": "commercial", "age_limit": 20},
        "RANGER 2": {"category": "commercial", "age_limit": 20},
        "RANGER-PRO": {"category": "commercial", "age_limit": 20},
        "SCANIA": {"category": "commercial", "age_limit": 30},
        "SELEGA": {"category": "commercial", "age_limit": 25},
        "SPACE RANGER": {"category": "commercial", "age_limit": 20},
        "SUPER DOLPHIN": {"category": "commercial", "age_limit": 30}
    },
    "NISSAN DIESEL (UD)": {
        "CONDOR": {"category": "commercial", "age_limit": 25},
        "QUON": {"category": "commercial", "age_limit": 30}
    },
    "MITSUOKA": {
        "BUDDY": {"category": "cars", "age_limit": 6},
        "GALUE": {"category": "cars", "age_limit": 6},
        "GALUE CLASSIC": {"category": "cars", "age_limit": 6},
        "GALUE II": {"category": "cars", "age_limit": 6},
        "HIMIKO": {"category": "cars", "age_limit": 6},
        "LE-SEYDE": {"category": "cars", "age_limit": 6},
        "NOUERA": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "ROCKSTAR": {"category": "cars", "age_limit": 6},
        "RYOGA": {"category": "cars", "age_limit": 6},
        "VIEWT": {"category": "cars", "age_limit": 6},
        "VIEWT STORY": {"category": "cars", "age_limit": 6},
        "ZERO ONE": {"category": "cars", "age_limit": 6}
    },
    "AUDI": {
        "A1": {"category": "cars", "age_limit": 6},
        "A1 SPORTBACK": {"category": "cars", "age_limit": 6},
        "A2": {"category": "cars", "age_limit": 6},
        "A3": {"category": "cars", "age_limit": 6},
        "A3 SEDAN": {"category": "cars", "age_limit": 6},
        "A4": {"category": "cars", "age_limit": 6},
        "A4 ALL ROAD QUATTRO": {"category": "cars", "age_limit": 6},
        "A4 AVANTE": {"category": "cars", "age_limit": 6},
        "A5": {"category": "cars", "age_limit": 6},
        "A5 SPORTBACK": {"category": "cars", "age_limit": 6},
        "A6": {"category": "cars", "age_limit": 6},
        "A6 ALLROAD QUATTRO": {"category": "cars", "age_limit": 6},
        "A6 AVANTE": {"category": "cars", "age_limit": 6},
        "A7": {"category": "cars", "age_limit": 6},
        "A7 SPORTBACK": {"category": "cars", "age_limit": 6},
        "A8": {"category": "cars", "age_limit": 6},
        "CABRIOLET": {"category": "cars", "age_limit": 6},
        "E-TRON GT QUATTRO": {"category": "cars", "age_limit": 6},
        "E-TRON SPORTBACK": {"category": "cars", "age_limit": 6},
        "Q2": {"category": "cars", "age_limit": 6},
        "Q3": {"category": "cars", "age_limit": 6},
        "Q4 E-TRON": {"category": "cars", "age_limit": 6},
        "Q4 SPORTBACK E-TRON": {"category": "cars", "age_limit": 6},
        "Q5": {"category": "cars", "age_limit": 6},
        "Q5 SPORTBACK": {"category": "cars", "age_limit": 6},
        "Q7": {"category": "cars", "age_limit": 6},
        "Q8": {"category": "cars", "age_limit": 6},
        "Q8 E-TRON": {"category": "cars", "age_limit": 6},
        "Q8 SPORTBACK E-TRON": {"category": "cars", "age_limit": 6},
        "R8": {"category": "cars", "age_limit": 6},
        "R8 SPIDER": {"category": "cars", "age_limit": 6},
        "RS 5 SPORTBACK": {"category": "cars", "age_limit": 6},
        "RS E-TRON GT": {"category": "cars", "age_limit": 6},
        "RS Q3": {"category": "cars", "age_limit": 6},
        "RS Q8": {"category": "cars", "age_limit": 6},
        "RS3": {"category": "cars", "age_limit": 6},
        "RS3 SPORTBACK": {"category": "cars", "age_limit": 6},
        "RS4 AVANTE": {"category": "cars", "age_limit": 6},
        "RS5": {"category": "cars", "age_limit": 6},
        "RS6": {"category": "cars", "age_limit": 6},
        "RS6 AVANTE": {"category": "cars", "age_limit": 6},
        "RS7 SPORTBACK": {"category": "cars", "age_limit": 6},
        "S1": {"category": "cars", "age_limit": 6},
        "S1 SPORTBACK": {"category": "cars", "age_limit": 6},
        "S3": {"category": "cars", "age_limit": 6},
        "S3 SEDAN": {"category": "cars", "age_limit": 6},
        "S4": {"category": "cars", "age_limit": 6},
        "S4 AVANTE": {"category": "cars", "age_limit": 6},
        "S5": {"category": "cars", "age_limit": 6},
        "S5 CABRIO": {"category": "cars", "age_limit": 6},
        "S5 SPORTBACK": {"category": "cars", "age_limit": 6},
        "S6": {"category": "cars", "age_limit": 6},
        "S6 AVANTE": {"category": "cars", "age_limit": 6},
        "S7 SPORTBACK": {"category": "cars", "age_limit": 6},
        "S8": {"category": "cars", "age_limit": 6},
        "SQ2": {"category": "cars", "age_limit": 6},
        "SQ5": {"category": "cars", "age_limit": 6},
        "SQ7": {"category": "cars", "age_limit": 6},
        "TT": {"category": "cars", "age_limit": 6},
        "TT ROADSTER": {"category": "cars", "age_limit": 6},
        "TTCOUPE": {"category": "cars", "age_limit": 6},
        "TTS COUPE": {"category": "cars", "age_limit": 6}
    },
    "BMW": {
        "1 SERIES": {"category": "cars", "age_limit": 6},
        "2 SERIES": {"category": "cars", "age_limit": 6},
        "3 SERIES": {"category": "cars", "age_limit": 6},
        "4 SERIES": {"category": "cars", "age_limit": 6},
        "5 SERIES": {"category": "cars", "age_limit": 6},
        "6 SERIES": {"category": "cars", "age_limit": 6},
        "7 SERIES": {"category": "cars", "age_limit": 6},
        "8 SERIES": {"category": "cars", "age_limit": 6},
        "I3": {"category": "cars", "age_limit": 6},
        "I4": {"category": "cars", "age_limit": 6},
        "I5": {"category": "cars", "age_limit": 6},
        "I7": {"category": "cars", "age_limit": 6},
        "I8": {"category": "cars", "age_limit": 6},
        "IX": {"category": "cars", "age_limit": 6},
        "IX1": {"category": "cars", "age_limit": 6},
        "IX2": {"category": "cars", "age_limit": 6},
        "IX3": {"category": "cars", "age_limit": 6},
        "M COUPE": {"category": "cars", "age_limit": 6},
        "M2": {"category": "cars", "age_limit": 6},
        "M3": {"category": "cars", "age_limit": 6},
        "M4": {"category": "cars", "age_limit": 6},
        "M5": {"category": "cars", "age_limit": 6},
        "M6": {"category": "cars", "age_limit": 6},
        "M8": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "X1": {"category": "cars", "age_limit": 6},
        "X2": {"category": "cars", "age_limit": 6},
        "X3": {"category": "cars", "age_limit": 6},
        "X4": {"category": "cars", "age_limit": 6},
        "X4 M": {"category": "cars", "age_limit": 6},
        "X5": {"category": "cars", "age_limit": 6},
        "X5 M": {"category": "cars", "age_limit": 6},
        "X6": {"category": "cars", "age_limit": 6},
        "X6 M": {"category": "cars", "age_limit": 6},
        "X7": {"category": "cars", "age_limit": 6},
        "Z3 COUPE": {"category": "cars", "age_limit": 6},
        "Z3 ROADSTER": {"category": "cars", "age_limit": 6},
        "Z4": {"category": "cars", "age_limit": 6}
    },
    "BMW ALPINA": {
        "B3": {"category": "cars", "age_limit": 6},
        "B4": {"category": "cars", "age_limit": 6},
        "B5": {"category": "cars", "age_limit": 6},
        "B7": {"category": "cars", "age_limit": 6},
        "D3": {"category": "cars", "age_limit": 6},
        "D5": {"category": "cars", "age_limit": 6},
        "XB7": {"category": "cars", "age_limit": 6},
        "XD3": {"category": "cars", "age_limit": 6},
        "XD4": {"category": "cars", "age_limit": 6}
    },
    "MERCEDES BENZ": {
        "190 CLASS": {"category": "cars", "age_limit": 6},
        "A CLASS": {"category": "cars", "age_limit": 6},
        "ACTROS": {"category": "commercial", "age_limit": 30},
        "AMG A CLASS": {"category": "cars", "age_limit": 6},
        "AMG C": {"category": "cars", "age_limit": 6},
        "AMG C CLASS": {"category": "cars", "age_limit": 6},
        "AMG C CLASS STATION WAGON": {"category": "cars", "age_limit": 6},
        "AMG CL": {"category": "cars", "age_limit": 6},
        "AMG CLA": {"category": "cars", "age_limit": 6},
        "AMG CLA SHOOTING BRAKE": {"category": "cars", "age_limit": 6},
        "AMG CLS": {"category": "cars", "age_limit": 6},
        "AMG CLS SHOOTING BRAKE": {"category": "cars", "age_limit": 6},
        "AMG E CLASS": {"category": "cars", "age_limit": 6},
        "AMG G CLASS": {"category": "cars", "age_limit": 6},
        "AMG GL": {"category": "cars", "age_limit": 6},
        "AMG GLA": {"category": "cars", "age_limit": 6},
        "AMG GLC": {"category": "cars", "age_limit": 6},
        "AMG GLE": {"category": "cars", "age_limit": 6},
        "AMG GT": {"category": "cars", "age_limit": 6},
        "AMG GT S": {"category": "cars", "age_limit": 6},
        "AMG M CLASS": {"category": "cars", "age_limit": 6},
        "AMG S CLASS": {"category": "cars", "age_limit": 6},
        "AMG SL": {"category": "cars", "age_limit": 6},
        "AMG SLC": {"category": "cars", "age_limit": 6},
        "AMG SLK": {"category": "cars", "age_limit": 6},
        "B CLASS": {"category": "cars", "age_limit": 6},
        "C CLASS": {"category": "cars", "age_limit": 6},
        "C CLASS ALL-TERRAIN": {"category": "cars", "age_limit": 6},
        "C CLASS STATION WAGON": {"category": "cars", "age_limit": 6},
        "CL": {"category": "cars", "age_limit": 6},
        "CLA": {"category": "cars", "age_limit": 6},
        "CLA SHOOTING BRAKE": {"category": "cars", "age_limit": 6},
        "CLE": {"category": "cars", "age_limit": 6},
        "CLK": {"category": "cars", "age_limit": 6},
        "CLS CLASS": {"category": "cars", "age_limit": 6},
        "CLS SHOOTING BRAKE": {"category": "cars", "age_limit": 6},
        "E CLASS": {"category": "cars", "age_limit": 6},
        "E CLASS STATION WAGON": {"category": "cars", "age_limit": 6},
        "E-CLASS ALL-TERRAIN": {"category": "cars", "age_limit": 6},
        "EQA": {"category": "cars", "age_limit": 6},
        "EQB": {"category": "cars", "age_limit": 6},
        "EQC": {"category": "cars", "age_limit": 6},
        "EQE": {"category": "cars", "age_limit": 6},
        "EQE SUV": {"category": "cars", "age_limit": 6},
        "EQS": {"category": "cars", "age_limit": 6},
        "EQS SUV": {"category": "cars", "age_limit": 6},
        "G CLASS": {"category": "cars", "age_limit": 6},
        "GELANDEWAGEN": {"category": "cars", "age_limit": 6},
        "GL": {"category": "cars", "age_limit": 6},
        "GLA": {"category": "cars", "age_limit": 6},
        "GLB": {"category": "cars", "age_limit": 6},
        "GLC": {"category": "cars", "age_limit": 6},
        "GLE": {"category": "cars", "age_limit": 6},
        "GLK": {"category": "cars", "age_limit": 6},
        "GLS": {"category": "cars", "age_limit": 6},
        "M CLASS": {"category": "cars", "age_limit": 6},
        "MEDIUM CLASS": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "R CLASS": {"category": "cars", "age_limit": 6},
        "S CLASS": {"category": "cars", "age_limit": 6},
        "SL": {"category": "cars", "age_limit": 6},
        "SLC": {"category": "cars", "age_limit": 6},
        "SLK": {"category": "cars", "age_limit": 6},
        "TRANSPORTER": {"category": "light_commercial", "age_limit": 10},
        "V CLASS": {"category": "cars", "age_limit": 6}
    },
    "VOLKSWAGEN": {
        "ARTEON": {"category": "cars", "age_limit": 6},
        "ARTEON SHOOTING BRAKE": {"category": "cars", "age_limit": 6},
        "BEETLE": {"category": "cars", "age_limit": 6},
        "CARAVELLE": {"category": "cars", "age_limit": 6},
        "CC": {"category": "cars", "age_limit": 6},
        "E-GOLF": {"category": "cars", "age_limit": 6},
        "EOS": {"category": "cars", "age_limit": 6},
        "GOLF": {"category": "cars", "age_limit": 6},
        "GOLF ALLTRACK": {"category": "cars", "age_limit": 6},
        "GOLF CABRIO": {"category": "cars", "age_limit": 6},
        "GOLF CABRIOLET": {"category": "cars", "age_limit": 6},
        "GOLF GTE": {"category": "cars", "age_limit": 6},
        "GOLF GTI": {"category": "cars", "age_limit": 6},
        "GOLF PLUS": {"category": "cars", "age_limit": 6},
        "GOLF R": {"category": "cars", "age_limit": 6},
        "GOLF R VALIANT": {"category": "cars", "age_limit": 6},
        "GOLF TOURAN": {"category": "cars", "age_limit": 6},
        "GOLF VARIANT": {"category": "cars", "age_limit": 6},
        "GOLF WAGON": {"category": "cars", "age_limit": 6},
        "ID.4": {"category": "cars", "age_limit": 6},
        "JETTA": {"category": "cars", "age_limit": 6},
        "LUPO": {"category": "cars", "age_limit": 6},
        "NEW BEETLE": {"category": "cars", "age_limit": 6},
        "NEW BEETLE CABRIOLET": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "PASSAT": {"category": "cars", "age_limit": 6},
        "PASSAT ALLTRACK": {"category": "cars", "age_limit": 6},
        "PASSAT CC": {"category": "cars", "age_limit": 6},
        "PASSAT GTE": {"category": "cars", "age_limit": 6},
        "PASSAT GTE VARIANT": {"category": "cars", "age_limit": 6},
        "PASSAT VARIANT": {"category": "cars", "age_limit": 6},
        "POLO": {"category": "cars", "age_limit": 6},
        "POLO GTI": {"category": "cars", "age_limit": 6},
        "SHARAN": {"category": "cars", "age_limit": 6},
        "SIROCCO": {"category": "cars", "age_limit": 6},
        "T-CROSS": {"category": "cars", "age_limit": 6},
        "T-ROC": {"category": "cars", "age_limit": 6},
        "THE BEETLE": {"category": "cars", "age_limit": 6},
        "THE BEETLE CABRIOLET": {"category": "cars", "age_limit": 6},
        "TIGUAN": {"category": "cars", "age_limit": 6},
        "TOUAREG": {"category": "cars", "age_limit": 6},
        "UP!": {"category": "cars", "age_limit": 6},
        "VANAGON": {"category": "light_commercial", "age_limit": 10}
    },
    "PORSCHE": {
        "718 BOXSTER": {"category": "cars", "age_limit": 6},
        "718 CAYMAN": {"category": "cars", "age_limit": 6},
        "718 SPYDER": {"category": "cars", "age_limit": 6},
        "911": {"category": "cars", "age_limit": 6},
        "928": {"category": "cars", "age_limit": 6},
        "BOXSTER": {"category": "cars", "age_limit": 6},
        "CAYENNE": {"category": "cars", "age_limit": 6},
        "CAYENNE COUPE": {"category": "cars", "age_limit": 6},
        "CAYMAN": {"category": "cars", "age_limit": 6},
        "MACAN": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "PANAMERA": {"category": "cars", "age_limit": 6},
        "TAYCAN": {"category": "cars", "age_limit": 6}
    },
    "OPEL": {
        "ASTRA": {"category": "cars", "age_limit": 6}
    },
    "SMART": {
        "COUPE": {"category": "cars", "age_limit": 6},
        "FORTWO CABRIO": {"category": "cars", "age_limit": 6},
        "FORTWO COUPE": {"category": "cars", "age_limit": 6},
        "FORTWO ELECTRIC DRIVE": {"category": "cars", "age_limit": 6},
        "FORTWO K": {"category": "cars", "age_limit": 6},
        "FOURFOUR": {"category": "cars", "age_limit": 6},
        "K": {"category": "cars", "age_limit": 6},
        "ROADSTER": {"category": "cars", "age_limit": 6}
    },
    "FORD": {
        "BRONCO": {"category": "cars", "age_limit": 6},
        "E350": {"category": "light_commercial", "age_limit": 10},
        "ECONOLINE": {"category": "light_commercial", "age_limit": 10},
        "ESCAPE": {"category": "cars", "age_limit": 6},
        "EXPLORER": {"category": "cars", "age_limit": 6},
        "EXPLORER SPORT TRACK": {"category": "light_commercial", "age_limit": 6},
        "F150": {"category": "light_commercial", "age_limit": 6},
        "F350": {"category": "light_commercial", "age_limit": 10},
        "FIESTA": {"category": "cars", "age_limit": 6},
        "KUGA": {"category": "cars", "age_limit": 6},
        "MUSTANG": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "TAURUS": {"category": "cars", "age_limit": 6}
    },
    "CHEVROLET": {
        "ASTRO": {"category": "light_commercial", "age_limit": 10},
        "CAMARO": {"category": "cars", "age_limit": 6},
        "CORVETTE": {"category": "cars", "age_limit": 6},
        "MW": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "SONIC": {"category": "cars", "age_limit": 6},
        "SUBURBAN": {"category": "cars", "age_limit": 6},
        "TAHOE SPORT": {"category": "cars", "age_limit": 6},
        "TRAIL BLAZER": {"category": "cars", "age_limit": 6}
    },
    "CADILLAC": {
        "ATS": {"category": "cars", "age_limit": 6},
        "CT5": {"category": "cars", "age_limit": 6},
        "CTS": {"category": "cars", "age_limit": 6},
        "CTS SPORT WAGON": {"category": "cars", "age_limit": 6},
        "DEVILLE": {"category": "cars", "age_limit": 6},
        "DTS": {"category": "cars", "age_limit": 6},
        "ESCALADE": {"category": "cars", "age_limit": 6},
        "FLEETWOOD": {"category": "cars", "age_limit": 6},
        "SEVILLE": {"category": "cars", "age_limit": 6},
        "SRX CROSSOVER": {"category": "cars", "age_limit": 6},
        "STS": {"category": "cars", "age_limit": 6},
        "XT4": {"category": "cars", "age_limit": 6},
        "XT5 CROSSOVER": {"category": "cars", "age_limit": 6},
        "XT6": {"category": "cars", "age_limit": 6}
    },
    "GMC": {
        "ACADIA": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "SAFARI": {"category": "light_commercial", "age_limit": 10},
        "SUBURBAN": {"category": "cars", "age_limit": 6},
        "TYPHOON": {"category": "light_commercial", "age_limit": 6},
        "YUKON": {"category": "cars", "age_limit": 6}
    },
    "BUICK": {
        "REGAL": {"category": "cars", "age_limit": 6}
    },
    "CHRYSLER": {
        "300": {"category": "cars", "age_limit": 6},
        "300C": {"category": "cars", "age_limit": 6},
        "CROSSFIRE": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "PT CRUISER": {"category": "cars", "age_limit": 6},
        "PT CRUISER CABRIO": {"category": "cars", "age_limit": 6},
        "WAGONEER": {"category": "cars", "age_limit": 6},
        "YPSILON": {"category": "cars", "age_limit": 6}
    },
    "DODGE": {
        "CHARGER": {"category": "cars", "age_limit": 6},
        "MAGNUM": {"category": "cars", "age_limit": 6},
        "NITRO": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6}
    },
    "JEEP": {
        "AVENGER": {"category": "cars", "age_limit": 6},
        "CHEROKEE": {"category": "cars", "age_limit": 6},
        "COMMANDER": {"category": "cars", "age_limit": 6},
        "COMPASS": {"category": "cars", "age_limit": 6},
        "GLADIATOR": {"category": "light_commercial", "age_limit": 6},
        "GRAND CHEROKEE": {"category": "cars", "age_limit": 6},
        "GRAND CHEROKEE L": {"category": "cars", "age_limit": 6},
        "PATRIOT": {"category": "cars", "age_limit": 6},
        "RENEGADE": {"category": "cars", "age_limit": 6},
        "RENEGADE 4XE": {"category": "cars", "age_limit": 6},
        "WRANGLER": {"category": "cars", "age_limit": 6},
        "WRANGLER UNLIMITED": {"category": "cars", "age_limit": 6}
    },
    "HUMMER": {
        "HUMMER": {"category": "cars", "age_limit": 6},
        "HUMMER H1": {"category": "cars", "age_limit": 6},
        "HUMMER H2": {"category": "cars", "age_limit": 6},
        "HUMMER H3": {"category": "cars", "age_limit": 6}
    },
    "LINCOLN": {
        "CONTINENTAL": {"category": "cars", "age_limit": 6},
        "MARK VIII": {"category": "cars", "age_limit": 6}
    },
    "TESLA": {
        "MODEL 3": {"category": "cars", "age_limit": 6},
        "MODEL S": {"category": "cars", "age_limit": 6},
        "MODEL X": {"category": "cars", "age_limit": 6}
    },
    "SATURN": {
        "AURA": {"category": "cars", "age_limit": 6}
    },
    "OLDSMOBILE": {
        "OTHER": {"category": "cars", "age_limit": 6}
    },
    "FERRARI": {
        "360": {"category": "cars", "age_limit": 6},
        "456": {"category": "cars", "age_limit": 6},
        "458 ITALIA": {"category": "cars", "age_limit": 6},
        "458 SPECIALE": {"category": "cars", "age_limit": 6},
        "458 SPIDER": {"category": "cars", "age_limit": 6},
        "488 SPIDER": {"category": "cars", "age_limit": 6},
        "488GTB": {"category": "cars", "age_limit": 6},
        "575": {"category": "cars", "age_limit": 6},
        "599": {"category": "cars", "age_limit": 6},
        "812GTS": {"category": "cars", "age_limit": 6},
        "CALIFORNIA": {"category": "cars", "age_limit": 6},
        "CALIFORNIA 30": {"category": "cars", "age_limit": 6},
        "CALIFORNIA T": {"category": "cars", "age_limit": 6},
        "F12 BERLINETTA": {"category": "cars", "age_limit": 6},
        "F348": {"category": "cars", "age_limit": 6},
        "F360": {"category": "cars", "age_limit": 6},
        "F430": {"category": "cars", "age_limit": 6},
        "F430 SPIDER": {"category": "cars", "age_limit": 6},
        "F8 SPIDER": {"category": "cars", "age_limit": 6},
        "F8TRIBUTO": {"category": "cars", "age_limit": 6},
        "FF": {"category": "cars", "age_limit": 6},
        "GTC4LUSSO": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "PORTOFINO": {"category": "cars", "age_limit": 6},
        "ROMA": {"category": "cars", "age_limit": 6},
        "SF90 SPIDER": {"category": "cars", "age_limit": 6},
        "SF90 STRADALE": {"category": "cars", "age_limit": 6}
    },
    "LAMBORGHINI": {
        "AVENTADOR": {"category": "cars", "age_limit": 6},
        "COUNTACH": {"category": "cars", "age_limit": 6},
        "GALLARDO": {"category": "cars", "age_limit": 6},
        "GALLARDO SPIDER": {"category": "cars", "age_limit": 6},
        "HURACAN": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "URUS": {"category": "cars", "age_limit": 6}
    },
    "MASERATI": {
        "222": {"category": "cars", "age_limit": 6},
        "GHIBLI": {"category": "cars", "age_limit": 6},
        "GRANCABRIO": {"category": "cars", "age_limit": 6},
        "GRANSPORT": {"category": "cars", "age_limit": 6},
        "GRANTURISMO": {"category": "cars", "age_limit": 6},
        "GRECALE": {"category": "cars", "age_limit": 6},
        "LEVANTE": {"category": "cars", "age_limit": 6},
        "MC20": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "QUATTROPORTE": {"category": "cars", "age_limit": 6}
    },
    "ALFA ROMEO": {
        "147": {"category": "cars", "age_limit": 6},
        "155": {"category": "cars", "age_limit": 6},
        "156": {"category": "cars", "age_limit": 6},
        "159": {"category": "cars", "age_limit": 6},
        "159 SPORTWAGON": {"category": "cars", "age_limit": 6},
        "4C": {"category": "cars", "age_limit": 6},
        "BRERA": {"category": "cars", "age_limit": 6},
        "GIULIA": {"category": "cars", "age_limit": 6},
        "GIULIETTA": {"category": "cars", "age_limit": 6},
        "GT": {"category": "cars", "age_limit": 6},
        "GTV": {"category": "cars", "age_limit": 6},
        "MITO": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "SPIDER": {"category": "cars", "age_limit": 6},
        "STELVIO": {"category": "cars", "age_limit": 6},
        "TONALE": {"category": "cars", "age_limit": 6}
    },
    "FIAT": {
        "500": {"category": "cars", "age_limit": 6},
        "500E": {"category": "cars", "age_limit": 6},
        "500S": {"category": "cars", "age_limit": 6},
        "500X": {"category": "cars", "age_limit": 6},
        "ABARTH 124 SPIDER": {"category": "cars", "age_limit": 6},
        "ABARTH 500": {"category": "cars", "age_limit": 6},
        "ABARTH 500C": {"category": "cars", "age_limit": 6},
        "ABARTH 500E": {"category": "cars", "age_limit": 6},
        "ABARTH 595": {"category": "cars", "age_limit": 6},
        "ABARTH 595C": {"category": "cars", "age_limit": 6},
        "ABARTH 695": {"category": "cars", "age_limit": 6},
        "ABARTH 695 EDIZIONE MASERATI": {"category": "cars", "age_limit": 6},
        "ABARTH 695 TRIBUTO FERRARI": {"category": "cars", "age_limit": 6},
        "ABARTH 695C": {"category": "cars", "age_limit": 6},
        "ABARTH PUNTO EVO": {"category": "cars", "age_limit": 6},
        "BARCHETTA": {"category": "cars", "age_limit": 6},
        "COUPE FIAT": {"category": "cars", "age_limit": 6},
        "DOBLO": {"category": "light_commercial", "age_limit": 10},
        "DUCATO": {"category": "light_commercial", "age_limit": 10},
        "GRANDE PUNTO": {"category": "cars", "age_limit": 6},
        "MULTIPLA": {"category": "cars", "age_limit": 6},
        "NEW PANDA": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "PANDA": {"category": "cars", "age_limit": 6},
        "PUNTO EVO": {"category": "cars", "age_limit": 6},
        "TIPO": {"category": "cars", "age_limit": 6}
    },
    "LANCIA": {
        "DELTA": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "YPSILON": {"category": "cars", "age_limit": 6}
    },
    "CITROEN": {
        "AX": {"category": "cars", "age_limit": 6},
        "BERLINGO": {"category": "light_commercial", "age_limit": 10},
        "BX": {"category": "cars", "age_limit": 6},
        "C3": {"category": "cars", "age_limit": 6},
        "C3 AIRCROSS": {"category": "cars", "age_limit": 6},
        "C4": {"category": "cars", "age_limit": 6},
        "C4 CACTUS": {"category": "cars", "age_limit": 6},
        "C4 PICASSO": {"category": "cars", "age_limit": 6},
        "C5": {"category": "cars", "age_limit": 6},
        "C5 AIRCROSS": {"category": "cars", "age_limit": 6},
        "C5 X": {"category": "cars", "age_limit": 6},
        "C6": {"category": "cars", "age_limit": 6},
        "DS 3 CROSSBACK E-TENSE": {"category": "cars", "age_limit": 6},
        "DS3": {"category": "cars", "age_limit": 6},
        "DS3 CABRIO": {"category": "cars", "age_limit": 6},
        "DS3 CROSSBACK": {"category": "cars", "age_limit": 6},
        "DS4": {"category": "cars", "age_limit": 6},
        "DS5": {"category": "cars", "age_limit": 6},
        "DS7 CROSSBACK": {"category": "cars", "age_limit": 6},
        "E-C4": {"category": "cars", "age_limit": 6},
        "GRAND C4 PICASSO": {"category": "cars", "age_limit": 6},
        "GRAND C4 SPACETOURER": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "ZX": {"category": "cars", "age_limit": 6}
    },
    "PEUGEOT": {
        "1007": {"category": "cars", "age_limit": 6},
        "106": {"category": "cars", "age_limit": 6},
        "2008": {"category": "cars", "age_limit": 6},
        "206": {"category": "cars", "age_limit": 6},
        "207": {"category": "cars", "age_limit": 6},
        "208": {"category": "cars", "age_limit": 6},
        "3008": {"category": "cars", "age_limit": 6},
        "307": {"category": "cars", "age_limit": 6},
        "308": {"category": "cars", "age_limit": 6},
        "406": {"category": "cars", "age_limit": 6},
        "407": {"category": "cars", "age_limit": 6},
        "408": {"category": "cars", "age_limit": 6},
        "5008": {"category": "cars", "age_limit": 6},
        "508": {"category": "cars", "age_limit": 6},
        "E-2008": {"category": "cars", "age_limit": 6},
        "E-208": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "RCZ": {"category": "cars", "age_limit": 6},
        "RIFTER": {"category": "light_commercial", "age_limit": 10}
    },
    "RENAULT": {
        "ALPINE A110": {"category": "cars", "age_limit": 6},
        "ARCANA": {"category": "cars", "age_limit": 6},
        "AVANTIME": {"category": "cars", "age_limit": 6},
        "CAPTUR": {"category": "cars", "age_limit": 6},
        "KADJAR": {"category": "cars", "age_limit": 6},
        "KANGOO": {"category": "light_commercial", "age_limit": 10},
        "KOLEOS": {"category": "cars", "age_limit": 6},
        "LUTECIA": {"category": "cars", "age_limit": 6},
        "MEGANE": {"category": "cars", "age_limit": 6},
        "MEGANE ESTATE": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "TWINGO": {"category": "cars", "age_limit": 6}
    },
    "JAGUAR": {
        "E-PACE": {"category": "cars", "age_limit": 6},
        "F-PACE": {"category": "cars", "age_limit": 6},
        "F-TYPE": {"category": "cars", "age_limit": 6},
        "I-PACE": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "S TYPE": {"category": "cars", "age_limit": 6},
        "SOVEREIGN": {"category": "cars", "age_limit": 6},
        "X TYPE": {"category": "cars", "age_limit": 6},
        "XE": {"category": "cars", "age_limit": 6},
        "XF": {"category": "cars", "age_limit": 6},
        "XJ6": {"category": "cars", "age_limit": 6},
        "XK": {"category": "cars", "age_limit": 6}
    },
    "LAND ROVER": {
        "DEFENDER": {"category": "cars", "age_limit": 6},
        "DISCOVERY": {"category": "cars", "age_limit": 6},
        "DISCOVERY 3": {"category": "cars", "age_limit": 6},
        "DISCOVERY 4": {"category": "cars", "age_limit": 6},
        "DISCOVERY SPORT": {"category": "cars", "age_limit": 6},
        "FREELANDER": {"category": "cars", "age_limit": 6},
        "FREELANDER 2": {"category": "cars", "age_limit": 6},
        "RANGE ROVER": {"category": "cars", "age_limit": 6},
        "RANGE ROVER EVOQUE": {"category": "cars", "age_limit": 6},
        "RANGE ROVER SPORT": {"category": "cars", "age_limit": 6},
        "RANGE ROVER VELAR": {"category": "cars", "age_limit": 6},
        "RANGE ROVER VOGUE": {"category": "cars", "age_limit": 6}
    },
    "LOTUS": {
        "ELETRE": {"category": "cars", "age_limit": 6},
        "ELISE": {"category": "cars", "age_limit": 6},
        "EMEYA": {"category": "cars", "age_limit": 6},
        "EMIRA": {"category": "cars", "age_limit": 6},
        "EVORA": {"category": "cars", "age_limit": 6},
        "EXIGE": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "SUPER 7": {"category": "cars", "age_limit": 6}
    },
    "ASTON MARTIN": {
        "DB7": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "VANTAGE": {"category": "cars", "age_limit": 6}
    },
    "BENTLEY": {
        "BENTAYGA": {"category": "cars", "age_limit": 6},
        "CONTINENTAL": {"category": "cars", "age_limit": 6},
        "FLYING SPUR": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6}
    },
    "ROLLS ROYCE": {
        "CORNICHE": {"category": "cars", "age_limit": 6},
        "CULLINAN": {"category": "cars", "age_limit": 6},
        "DAWN": {"category": "cars", "age_limit": 6},
        "GHOST": {"category": "cars", "age_limit": 6},
        "ROLLS ROYCE": {"category": "cars", "age_limit": 6},
        "WRAITH": {"category": "cars", "age_limit": 6}
    },
    "MINI": {
        "MINI": {"category": "cars", "age_limit": 6}
    },
    "MG": {
        "MGF": {"category": "cars", "age_limit": 6},
        "TF": {"category": "cars", "age_limit": 6}
    },
    "ROVER": {
        "75": {"category": "cars", "age_limit": 6},
        "MINI": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6}
    },
    "DAIMLER": {
        "DAIMLER": {"category": "cars", "age_limit": 6},
        "DOUBLE SIX": {"category": "cars", "age_limit": 6}
    },
    "MCLAREN": {
        "600LT": {"category": "cars", "age_limit": 6},
        "650S": {"category": "cars", "age_limit": 6},
        "720S": {"category": "cars", "age_limit": 6}
    },
    "VOLVO": {
        "240": {"category": "cars", "age_limit": 6},
        "740": {"category": "cars", "age_limit": 6},
        "850": {"category": "cars", "age_limit": 6},
        "850 ESTATE": {"category": "cars", "age_limit": 6},
        "940": {"category": "cars", "age_limit": 6},
        "940 ESTATE": {"category": "cars", "age_limit": 6},
        "960": {"category": "cars", "age_limit": 6},
        "C30": {"category": "cars", "age_limit": 6},
        "C40": {"category": "cars", "age_limit": 6},
        "C40 RECHARGE": {"category": "cars", "age_limit": 6},
        "C70": {"category": "cars", "age_limit": 6},
        "EX30": {"category": "cars", "age_limit": 6},
        "OTHER": {"category": "cars", "age_limit": 6},
        "S60": {"category": "cars", "age_limit": 6},
        "S90": {"category": "cars", "age_limit": 6},
        "V40": {"category": "cars", "age_limit": 6},
        "V50": {"category": "cars", "age_limit": 6},
        "V60": {"category": "cars", "age_limit": 6},
        "V70": {"category": "cars", "age_limit": 6},
        "V90": {"category": "cars", "age_limit": 6},
        "XC40": {"category": "cars", "age_limit": 6},
        "XC40 RECHARGE": {"category": "cars", "age_limit": 6},
        "XC60": {"category": "cars", "age_limit": 6},
        "XC70": {"category": "cars", "age_limit": 6},
        "XC90": {"category": "cars", "age_limit": 6}
    },
    "SAAB": {
        "9-3": {"category": "cars", "age_limit": 6},
        "900": {"category": "cars", "age_limit": 6}
    },
    "HYUNDAI": {
        "COUPE": {"category": "cars", "age_limit": 6},
        "I30": {"category": "cars", "age_limit": 6},
        "IONIQ 5": {"category": "cars", "age_limit": 6},
        "KONA": {"category": "cars", "age_limit": 6}
    },
    "HITACHI": {
        "OTHER": {"category": "heavy_duty", "age_limit": 30}
    },
    "KATO": {
        "OTHER": {"category": "heavy_duty", "age_limit": 30}
    },
    "KOBELCO": {
        "OTHER": {"category": "heavy_duty", "age_limit": 30}
    },
    "KOMATSU": {
        "OTHER": {"category": "heavy_duty", "age_limit": 30}
    },
    "KUBOTA": {
        "KUBOTA": {"category": "heavy_duty", "age_limit": 30}
    },
    "SUMITOMO": {
        "OTHER": {"category": "heavy_duty", "age_limit": 30}
    },
    "TADANO": {
        "OTHER": {"category": "heavy_duty", "age_limit": 30}
    },
    "TCM": {
        "OTHER": {"category": "heavy_duty", "age_limit": 30}
    },
    "YANMAR": {
        "OTHER": {"category": "heavy_duty", "age_limit": 30}
    },
    "OTHER TECHNICS": {
        "OTHER": {"category": "heavy_duty", "age_limit": 30}
    },
    "YAMAHA": {
        "BIKE": {"category": "motorcycles_atvs", "age_limit": 5},
        "OTHER": {"category": "heavy_duty", "age_limit": 30}
    },
    "OTHER": {
        "OTHER": {"category": "cars", "age_limit": 6}
    }
}